### ISSUE TITLE
inaccurate description of CompCert

### ISSUE THREAD

**Issue by Smattr** [ymanerka/pipeproof#1]
Very impressive work! This project takes a very interesting approach.

In the readme, there is a reference to a compiler that I think is [CompCert](http://compcert.inria.fr) that says:

> ...C compilers which provably produce correct C code...

The compiler takes C code as input but *produces* machine code. Or maybe more accurately, assembly as I don't think the verification covers assembling and linking. Is this correct or perhaps I have misinterpreted something?

**Comment by ymanerka** [comment]
Better late than never :).
